heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files
  path: /usr/share/heartbeat/monitors.d/*.yml
  # If enabled, heartbeat will periodically check the config.monitors path for changes
  reload.enabled: true
  # How often to check for changes
  reload.period: 1s

output.elasticsearch.hosts:
  - elasticsearch:9200